namespace: "ansible_collection"
name: "pan"
description: "Ansible modules for Palo Alto Networks NGFWs"
authors:
  - "Ivan Bojer <>"
version: "0.1.5"
license:
  - "BSD-3-Clause"
readme: "README.md"
tags:
  - certified
  - network
