namespace: "notalikins"
name: "pan"
description: "Fork of Ansible modules for Palo Alto Networks NGFWs"
authors:
  - "Ivan Bojer <>"
version: "0.1.3"
license:
  - "BSD-3-Clause"
readme: "README.md"
tags:
  - certified
  - network
